### get all the users
GET http://localhost:3001/api/users/ HTTP/1.1

### create a user
POST http://localhost:3001/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Gerad",
    "lastName": "pique",
    "email": "pique@gmail.com",
    "password": "asd"
}


### - get a single 
GET http://localhost:3001/api/users/60850c6d0010da19c85db1da


### - add a friend -- userId, FriendId
PUT http://localhost:3001/api/users/friend/add
Content-Type: application/json

{
    "id": "60839f65d4437f25d430359f",
    "FriendId": "60839f2fd4437f25d430359d"
}

### login user
POST http://localhost:3001/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "angel@gmail.com",
    "password": "asd"
}


### updated user
PUT http://localhost:3001/api/users/60839f2fd4437f25d430359d HTTP/1.1
Content-Type: application/json

{
    "profile_photo": "/uploads/1619185589411.jfif"
}


### upload file 
POST http://localhost:3001/upload HTTP/1.1